FROM node:20-alpine

WORKDIR /usr/src/app

# Install dependencies for Prisma (openssl, etc.)
RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate --schema=./prisma/schema.prisma

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]