services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:betsie@postgres:5432/kanban?schema=public
    ports:
      - '5001:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: betsie
      POSTGRES_DB: kanban
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
