FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache openssl netcat-openbsd curl

COPY package.json package-lock.json ./
COPY prisma ./prisma/
COPY start.sh ./

RUN npm install && \
    npx prisma generate && \
    chmod +x start.sh 

COPY . .

EXPOSE 3000

CMD ["./start.sh"]