services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '5001:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
